sonar.projectKey=chaimaraz_autentiaQA-Front
sonar.organization=chaimaraz

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/coverage/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/autentia-front/lcov.info
